package com.myapps.toualbiamine.food2class.ViewHolder;

import android.support.annotation.NonNull;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import com.myapps.toualbiamine.food2class.Interface.ItemClickListener;
import com.myapps.toualbiamine.food2class.R;

public class MenuViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {

    public TextView menuName;
    public ImageView menuImg;

    private ItemClickListener itemClickListener;

    //Autogenerated.
    public MenuViewHolder(@NonNull View itemView) {
        super(itemView);

        menuName = (TextView) itemView.findViewById(R.id.menuName);
        menuImg = (ImageView) itemView.findViewById(R.id.menuImg);

        itemView.setOnClickListener(this);

    }

    public void setItemClickListener(ItemClickListener itemClickListener) {
        this.itemClickListener = itemClickListener;
    }

    @Override
    public void onClick(View v) {

        itemClickListener.onClick(v, getAdapterPosition(), false);

    }


}
